apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  flexVolume:
    #driver: "5pi.de/do-volume"
    driver: "tonyzou/digitalocean"
    fsType: ext4
    secretRef:
      name: do-api-key
    options:
      volumeId: "${DO_VOLUME_MYSQL_ID}"
      
