apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: "5pi.de/do-volume"
    fsType: ext4
    options:
      volume: "mysql"
      
